### ISSUE TITLE
Something wrong with test and ground truth pair!

### ISSUE THREAD

**Issue by SunnysideBao** [hcw-00/STPM_anomaly_detection#5]
Hello, this error occurs when running the program, why ?Thanks

![X0 4%9QUVR$@RX1%T8~ X$W](https://user-images.githubusercontent.com/39000707/114857166-8b662e80-9e1a-11eb-9854-7cb3d985519f.png)

**Comment by hcw-00** [comment]
Hi. Try after comment out that line. "assert os.path....".
I will fix that. Thanks.

**Comment by hcw-00** [comment]
Hi. Try after comment out that line. "assert os.path....".
I will fix that. Thanks.
