### ISSUE TITLE
pretrained weights ?

### ISSUE THREAD

**Issue by trungpham2606** [hcw-00/STPM_anomaly_detection#6]
Dear @hcw-00 ,
I want to test your great work. Can you provide the pretrained weights ?

**Comment by hcw-00** [comment]
Hi. It will takes just few minutes to train a category. But if you need plz tell me which categories you need. not all.

**Comment by hcw-00** [comment]
Hello. Thank you for your interest.
It would take around 10min. to train a category.
But if you tell me I can upload some pretrained weights. not all.
Just tell me which categories you need.
Thanks.

and don't forget to click star button :-)

2021년 5월 28일 (금) 오후 5:43, trungpham2606 ***@***.***>님이 작성:

**Comment by hcw-00** [comment]
I uploaded on weights directory.
