### ISSUE TITLE
[fix] error caused by transform order

### ISSUE THREAD

**Issue by Yuichi-Nakababayashi** [hcw-00/STPM_anomaly_detection#9]
I tried to run your code with my own datasets, and found it gives me the following error messages.
I could fix that error by changing the order of transform.
I'd be glad if you could take a look at this message.
Code I run:
```
python train.py --phase 'train' --dataset_path 'my_path' --project_path './output'
```
The error I got:
```
TypeError: cannot unpack non-iterable builtin_function_or_method object
```

I switched  the order of `CenterCrop(input_size)` and `ToTensor()`, and everything worked well.

**Comment by hcw-00** [comment]
Information is not enough. Could you give me more information? 
I recommend you to try pytorch lightning version. It's much easier and stable. Iink is on README.md

**Comment by Yuichi-Nakababayashi** [comment]
Thank you very much for your reply.
I used torch=1.6.0
I simply thought you need to replace 
``` train.py
def data_transforms(load_size=256, mean_train=mean_train, std_train=std_train):
    data_transforms = transforms.Compose(
        [
            transforms.Resize((load_size, load_size), Image.ANTIALIAS),
            transforms.ToTensor(),
            transforms.CenterCrop(input_size),
            transforms.Normalize(mean=mean_train, std=std_train),
        ]
    )
    return data_transforms
```
with
``` train.py
def data_transforms(load_size=256, mean_train=mean_train, std_train=std_train):
    data_transforms = transforms.Compose(
        [
            transforms.Resize((load_size, load_size), Image.ANTIALIAS),
            transforms.CenterCrop(input_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=mean_train, std=std_train),
        ]
    )
    return data_transforms
```
However, I now understand that this issue is caused by the difference between pytorch and pytorch lightning.
Thank you.

**Comment by hcw-00** [comment]
Util now I've not encountered that problem. But I'm grad to hear that you solved the problem. 
Thank you.
